# Generated by Django 5.0.6 on 2024-05-08 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=8)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiator_connections', to='users.user')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_connections', to='users.user')),
            ],
            options={
                'unique_together': {('user1', 'user2')},
            },
        ),
    ]
